-- tim's server --

-- CREATE DATABASE TSQLL;
-- USE TSQLL;

-- SELECT name, database_id, create_date 
-- FROM sys.databases;

------ CHECK TABLES ----

-- SELECT * FROM SYSOBJECTS
-- WHERE xtype = 'U';

-- GO

-- SELECT * FROM CUSTOMER;


IF OBJECT_ID('Sale') IS NOT NULL
DROP TABLE SALE;

IF OBJECT_ID('Product') IS NOT NULL
DROP TABLE PRODUCT;

IF OBJECT_ID('Customer') IS NOT NULL
DROP TABLE CUSTOMER;

IF OBJECT_ID('Location') IS NOT NULL
DROP TABLE LOCATION;

GO

CREATE TABLE CUSTOMER (
CUSTID	INT
, CUSTNAME	NVARCHAR(100)
, SALES_YTD	MONEY
, STATUS	NVARCHAR(7)
, PRIMARY KEY	(CUSTID) 
);

CREATE TABLE PRODUCT (
PRODID	INT
, PRODNAME	NVARCHAR(100)
, SELLING_PRICE	MONEY
, SALES_YTD	MONEY
, PRIMARY KEY	(PRODID)
);

CREATE TABLE SALE (
SALEID	BIGINT
, CUSTID	INT
, PRODID	INT
, QTY	INT
, PRICE	MONEY
, SALEDATE	DATE
, PRIMARY KEY 	(SALEID)
, FOREIGN KEY 	(CUSTID) REFERENCES CUSTOMER
, FOREIGN KEY 	(PRODID) REFERENCES PRODUCT
);

CREATE TABLE LOCATION (
  LOCID	NVARCHAR(5)
, MINQTY	INTEGER
, MAXQTY	INTEGER
, PRIMARY KEY 	(LOCID)
, CONSTRAINT CHECK_LOCID_LENGTH CHECK (LEN(LOCID) = 5)
, CONSTRAINT CHECK_MINQTY_RANGE CHECK (MINQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_RANGE CHECK (MAXQTY BETWEEN 0 AND 999)
, CONSTRAINT CHECK_MAXQTY_GREATER_MIXQTY CHECK (MAXQTY >= MINQTY)
);

IF OBJECT_ID('SALE_SEQ') IS NOT NULL
DROP SEQUENCE SALE_SEQ;
CREATE SEQUENCE SALE_SEQ;

GO

-- ADD_CUSTOMER ------------------

IF OBJECT_ID('ADD_CUSTOMER') IS NOT NULL
DROP PROCEDURE ADD_CUSTOMER;
GO

CREATE PROCEDURE ADD_CUSTOMER @PCUSTID INT, @PCUSTNAME NVARCHAR(100) AS

BEGIN
    BEGIN TRY

        IF @PCUSTID < 1 OR @PCUSTID > 499
            THROW 50020, 'Customer ID out of range', 1

        INSERT INTO CUSTOMER (CUSTID, CUSTNAME, SALES_YTD, STATUS)
        VALUES (@PCUSTID, @PCUSTNAME, 0, 'OK');
    END TRY

    BEGIN CATCH
        IF ERROR_MESSAGE() = 2627
            THROW 50010, 'Duplicate customer ID', 1
        ELSE IF ERROR_NUMBER() = 50020
            THROW
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END;
        END CATCH;

END;

GO

EXEC ADD_CUSTOMER @PCUSTID = 1, @PCUSTNAME = 'TESTDUDE1';
EXEC ADD_CUSTOMER @PCUSTID = 66, @PCUSTNAME = 'TESTDUDE2';
EXEC ADD_CUSTOMER @PCUSTID = 499, @PCUSTNAME = 'TESTDUDE3';
SELECT * FROM CUSTOMER;

-- DELETE_ALL_CUSTOMERS ------------------

IF OBJECT_ID('DELETE_ALL_CUSTOMERS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_CUSTOMERS;

GO

CREATE PROCEDURE DELETE_ALL_CUSTOMERS AS

BEGIN
    BEGIN TRY
        DELETE FROM CUSTOMER;
        RETURN @@ROWCOUNT
    END TRY
    BEGIN CATCH
        BEGIN
            DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
            THROW 50000, @ERRORMESSAGE, 1
        END;
    END CATCH;
END;

GO

EXEC DELETE_ALL_CUSTOMERS;
SELECT * FROM CUSTOMER;

-- ADD_PRODUCT -------

IF OBJECT_ID('ADD_PRODUCT') IS NOT NULL
DROP PROCEDURE ADD_PRODUCT;

GO

CREATE PROCEDURE ADD_PRODUCT @PPRODID INT, @PPRODNAME NVARCHAR(100), @PPRICE MONEY AS

BEGIN
    BEGIN TRY
        IF @PPRODID < 1000 OR @PPRODID > 2500
            THROW 50040, 'Product ID out of range.', 1

            ELSE IF @PPRICE < 0 OR @PPRICE > 999.99
                THROW 50050, 'Price out of range.', 1

            INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD)
            VALUES (@PPRODID, @PPRODNAME, @PPRICE, 0);
    END TRY

    BEGIN CATCH
        DECLARE @ERRORmessage NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH;

END;

GO

EXEC ADD_PRODUCT @PPRODID = 1234, @PPRODNAME = "Dude Juice", @PPRICE = 33;
SELECT * FROM PRODUCT;

-- DELETE_ALL_PRODUCTS ------

IF OBJECT_ID('DELETE_ALL_PRODUCTS') IS NOT NULL
DROP PROCEDURE DELETE_ALL_PRODUCTS;

GO

CREATE PROCEDURE DELETE_ALL_PRODUCTS AS

BEGIN
    BEGIN TRY
        DELETE FROM PRODUCT;
        DECLARE @PRODROWSDELETED INT = @@ROWCOUNT;
        RETURN @@ROWCOUNT
    END TRY
    
    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END;

GO

EXEC DELETE_ALL_PRODUCTS;
SELECT * FROM PRODUCT;


-- GET_CUSTOMER_STRING ------

IF OBJECT_ID('GET_CUSTOMER_STRING') IS NOT NULL
DROP PROCEDURE GET_CUSTOMER_STRING;

GO

CREATE PROCEDURE GET_CUSTOMER_STRING 
    @PCUSTID INT, 
    @PRETURNSTRING NVARCHAR(1000) 
OUT AS

BEGIN
    BEGIN TRY
        DECLARE @CNAME NVARCHAR(100);
        DECLARE @STATUS NVARCHAR(7);
        DECLARE @SYTD MONEY;

        SELECT @CNAME = CUSTNAME, @STATUS = STATUS, @SYTD = SALES_YTD
        FROM CUSTOMER WHERE CUSTID = @PCUSTID;

        SET @PRETURNSTRING = CONCAT('CUSTID: ', @PCUSTID, 'NAME: ', @CNAME, 'STATUS: ', @STATUS, 'SALES YTD: ', @SYTD)
    END TRY

    BEGIN CATCH
        IF ERROR_NUMBER() = 2627
            THROW 50060, 'Customer ID not found', 1
                ELSE
                    BEGIN
                        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                        THROW 50000, @ERRORMESSAGE, 1
                    END;
     END CATCH;
END;

GO

INSERT INTO CUSTOMER (CUSTID, CUSTNAME, STATUS, SALES_YTD)
VALUES (66, 'FRANK OCEAN', 'M.I.A', 50)

DELETE FROM CUSTOMER
WHERE @CUSTID = 666;

SELECT * FROM CUSTOMER;

BEGIN
    DECLARE @RSTRING NVARCHAR(1000);
    SET @RSTRING = 'Original value';
    
    EXEC GET_CUSTOMER_STRING @PCUSTID = 222, @PRETURNSTRING = @RSTRING OUT;
    PRINT(@RSTRING);
END;

GO


-- UPD_CUST_SALESYTD ------

IF OBJECT_ID ('UPD_CUST_SALESYTD') IS NOT NULL
DROP PROCEDURE UPD_CUST_SALESYTD

GO

CREATE PROCEDURE UPD_CUST_SALESYTD 
    @PCUSTID INT, 
    @PAMT MONEY
AS

BEGIN
    BEGIN TRY
        IF @PAMT < -999.99 OR @PAMT > 999.99
            THROW 50080, 'Amount out of range', 1
            UPDATE CUSTOMER SET SALES_YTD = SALES_YTD + @PAMT
            WHERE CUSTID = @PCUSTID;
    END TRY
    
    BEGIN CATCH
        IF @@ROWCOUNT = 0
            THROW 50070, 'Customer ID not found', 1
            ELSE
                BEGIN
                    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                    THROW 50000, @ERRORMESSAGE, 1
                END;
    END CATCH
END;

EXEC UPD_CUST_SALESYTD @PCUSTID = 666, @PAMT = 22;
SELECT * FROM CUSTOMER;

GO

-- GET_PROD_STRING -----
                
IF OBJECT_ID('GET_PROD_STRING') IS NOT NULL
DROP PROCEDURE GET_PROD_STRING;

GO

CREATE PROCEDURE GET_PROD_STRING 
    @PPRODID INT, 
    @PRETURNSTRING NVARCHAR(1000) 
OUT AS

BEGIN
    BEGIN TRY
        DECLARE @PPRODNAME NVARCHAR(100);
        DECLARE @PPRICE MONEY;
        DECLARE @SYTD MONEY;

        SELECT @PPRODNAME = PRODNAME, @PPRICE = SELLING_PRICE, @SYTD = SALES_YTD
        FROM PRODUCT WHERE PRODID = @PPRODID;

        SET @PRETURNSTRING = CONCAT('PRODID: ', @PPRODID, 'NAME: ', @PPRODNAME, 'PRICE: ', @PPRICE, 'SALES YTD: ', @SYTD)
    END TRY

    BEGIN CATCH
        IF ERROR_NUMBER() = 2627
            THROW 50090, 'Product ID not found', 1
                ELSE
                    BEGIN
                        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                        THROW 50000, @ERRORMESSAGE, 1
                    END;
     END CATCH;
END;

GO

INSERT INTO PRODUCT (PRODID, PRODNAME, SELLING_PRICE, SALES_YTD)
VALUES (33, 'THREE SPICES', 10, 40)

BEGIN
    DECLARE @RSTRING NVARCHAR(1000);
    SET @RSTRING = 'Original value';
    
    EXEC GET_PROD_STRING @PPRODID = 33, @PRETURNSTRING = @RSTRING OUT;
    PRINT(@RSTRING);
END;

GO

SELECT * FROM PRODUCT;

-- UPD_PROD_SALESYTD -----

IF OBJECT_ID ('UPD_PROD_SALESYTD') IS NOT NULL
DROP PROCEDURE UPD_PROD_SALESYTD

GO

CREATE PROCEDURE UPD_PROD_SALESYTD 
    @PPRODID INT, 
    @PAMT MONEY
AS

BEGIN
    BEGIN TRY
        IF @PAMT < -999.99 OR @PAMT > 999.99
            THROW 50110, 'Amount out of range', 1
            UPDATE PRODUCT SET SALES_YTD = SALES_YTD + @PAMT
            WHERE PRODID = @PPRODID;
    END TRY
    
    BEGIN CATCH
        IF @@ROWCOUNT = 0
            THROW 50100, 'Product ID not found', 1
            ELSE
                BEGIN
                    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                    THROW 50000, @ERRORMESSAGE, 1
                END;
    END CATCH
END;

EXEC UPD_PROD_SALESYTD @PPRODID = 33, @PAMT = 22;
SELECT * FROM PRODUCT;

GO

-- UPD_CUSTOMER_STATUS -----

IF OBJECT_ID ('UPD_CUSTOMER_STATUS') IS NOT NULL
DROP PROCEDURE UPD_CUSTOMER_STATUS

GO

CREATE PROCEDURE UPD_CUSTOMER_STATUS 
    @PCUSTID INT, 
    @PSTATUS NVARCHAR
AS

BEGIN
    BEGIN TRY
        IF @PSTATUS <> 'OK' AND @PSTATUS <> 'SUSPEND'
            THROW 50130, 'Invalid status value', 1
            UPDATE CUSTOMER SET STATUS = @PSTATUS
            WHERE CUSTID = @PCUSTID;
    END TRY
    
    BEGIN CATCH
        IF @@ROWCOUNT = 0
            THROW 50120, 'Customer ID not found', 1
            ELSE
                BEGIN
                    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                    THROW 50000, @ERRORMESSAGE, 1
                END;
    END CATCH
END;

EXEC UPD_CUSTOMER_STATUS @PCUSTID = 666, @PSTATUS = 'MIA';
SELECT * FROM CUSTOMER;

GO

-- ADD_SIMPLE_SALE ------

IF OBJECT_ID('ADD_SIMPLE_SALE') IS NOT NULL
DROP PROCEDURE ADD_SIMPLE_SALE

GO

CREATE PROCEDURE ADD_SIMPLE_SALE
    @PCUSTID INT,
    @PPRODID INT,
    @PQTY INT
AS

BEGIN
    BEGIN TRY
        DECLARE @PRICE MONEY,
                @YTDTOTAL MONEY

        IF @PQTY < 1 OR @PQTY > 999
            THROW 50140, 'Sale quantity outside valid range', 1
        
        IF (SELECT STATUS FROM CUSTOMER WHERE CUSTID = @PCUSTID) != 'OK'
            THROW 50150, 'Customer status is not OK', 1

        IF NOT EXISTS (SELECT * FROM CUSTOMER WHERE CUSTID = @PCUSTID)
            THROW 50160, 'Customer ID not found', 1
        
        IF NOT EXISTS (SELECT * FROM PRODUCT WHERE PRODID = @PPRODID)
            THROW 50170, 'Product ID not found', 1
    
    SELECT @PRICE = SELLING_PRICE
    FROM PRODUCT
    WHERE PRODID = @PPRODID

    SET @YTDTOTAL = @PQTY * @PRICE

    EXEC UPD_CUST_SALESYTD @PCUSTID = @PCUSTID, @PAMT = @PQTY;
    EXEC UPD_PROD_SALESYTD @PPRODID = @PPRODID, @PAMT = @PQTY;

    END TRY
    
    BEGIN CATCH
        IF @@ROWCOUNT = 0
            THROW 50120, 'Customer ID not found', 1
            ELSE
                BEGIN
                    DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                    THROW 50000, @ERRORMESSAGE, 1
                END;
    END CATCH
END;

-- SUM_CUSTOMER_SALESYTD ------

IF OBJECT_ID('SUM_CUSTOMER_SALESYTD') IS NOT NULL
DROP PROCEDURE SUM_CUSTOMER_SALESYTD

GO

CREATE PROCEDURE SUM_CUSTOMER_SALESYTD

AS

BEGIN
    BEGIN TRY
        DECLARE @TOTAL INT
        SELECT @TOTAL = SUM(SALES_YTD)
        FROM
        CUSTOMER
    END TRY

    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
    RETURN @TOTAL
END

GO

-- SUM_PRODUCT_SALESYTD

IF OBJECT_ID('SUM_PRODUCT_SALESYTD') IS NOT NULL
DROP PROCEDURE SUM_PRODUCT_SALESYTD

GO

CREATE PROCEDURE SUM_PRODUCT_SALESYTD

AS

BEGIN
    BEGIN TRY
        DECLARE @TOTAL INT
        SELECT @TOTAL = SUM(SALES_YTD)
        FROM
        PRODUCT
    END TRY

    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
    RETURN @TOTAL
END

GO

-- GET_ALL_CUSTOMERS

IF OBJECT_ID('GET_ALL_CUSTOMERS') IS NOT NULL
DROP PROCEDURE GET_ALL_CUSTOMERS

GO

CREATE PROCEDURE GET_ALL_CUSTOMERS
    @POUTCUR CURSOR VARYING OUTPUT

AS
BEGIN
    BEGIN TRY
        SET @POUTCUR = CURSOR
        FOR
        SELECT * FROM CUSTOMER
        OPEN @POUTCUR
    END TRY

    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END

-- GET_ALL_PRODUCTS

IF OBJECT_ID('GET_ALL_PRODUCTS') IS NOT NULL
DROP PROCEDURE GET_ALL_PRODUCTS

GO

CREATE PROCEDURE GET_ALL_PRODUCTS
    @POUTCUR CURSOR VARYING OUTPUT

AS
BEGIN
    BEGIN TRY
        SET @POUTCUR = CURSOR
        FOR
        SELECT * FROM PRODUCT
        OPEN @POUTCUR
    END TRY

    BEGIN CATCH
        DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
        THROW 50000, @ERRORMESSAGE, 1
    END CATCH
END

-- ADD_LOCATION

IF OBJECT_ID('ADD_LOCATION') IS NOT NULL
DROP PROCEDURE ADD_LOCATION

GO

CREATE PROCEDURE ADD_LOCATION
    @PLOCCODE NVARCHAR,
    @PMINQTY INT,
    @PMAXQTY INT

AS

BEGIN
    BEGIN TRY
        IF LEN(@PLOCCODE) != 5
            THROW 50190, 'Location code length invalid', 1
        IF @PMINQTY < 0
            THROW 50200, 'Minimum Qty out of range', 1
        IF @PMAXQTY > 999
            THROW 50210, 'Maximum Qty out of range', 1
        IF @PMAXQTY >= @PMINQTY
            THROW 50220, 'Minimum Qty larger than Maximum Qty', 1
        
        INSERT INTO LOCATION (LOCID, MINQTY, MAXQTY)
        VALUES (@PLOCCODE, @PMINQTY, @PMINQTY)
    END TRY

    BEGIN CATCH
        IF ERROR_MESSAGE() = 2627
            THROW 50180, 'Duplicate customer ID', 1
        ELSE
            BEGIN
                DECLARE @ERRORMESSAGE NVARCHAR(MAX) = ERROR_MESSAGE();
                THROW 50000, @ERRORMESSAGE, 1
            END
    END CATCH
END;